version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    environment:
      DEFAULT_DB_URI: postgres://postgres:@db:5432/postgres
    command: ["./deploy/wait-for-it.sh", "db:5432", "--", "./deploy/entrypoint.sh"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
