[project]
name = "data-ui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2",
    "django-debug-toolbar>=5.2.0",
    "django-environ>=0.12.0",
    "django-import-export>=4.3.7",
    "django-simple-history>=3.8.0",
    "django-tastypie>=0.15.1",
    "gunicorn>=23.0.0",
    "mysqlclient>=2.2.7",
    "psycopg2-binary>=2.9.10",
    "pylint>=3.3.6",
    "pymysql>=1.1.1",
    "setuptools>=80.0.1",
    "sqlparse>=0.5.3",
    "whitenoise>=6.9.0",
    "zappa>=0.59.0",
]

[dependency-groups]
dev = [
    "yapf>=0.43.0",
]
