# Generated by Django 2.0.4 on 2018-04-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'managed': True, 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='employees',
            options={'managed': True, 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='finances',
            options={'managed': True, 'verbose_name_plural': 'Finances'},
        ),
        migrations.AlterModelOptions(
            name='nonprofitfinances',
            options={'managed': True, 'verbose_name_plural': 'NonProfit Finances'},
        ),
        migrations.AlterModelOptions(
            name='nonprofitsalary',
            options={'managed': True, 'verbose_name_plural': 'NonProfit Salaries'},
        ),
        migrations.AlterModelOptions(
            name='officer',
            options={'managed': True, 'verbose_name_plural': 'Officers'},
        ),
        migrations.AlterModelOptions(
            name='officersalary',
            options={'managed': True, 'verbose_name_plural': 'Officer Salaries'},
        ),
    ]
