# Generated by Django 2.0.4 on 2018-05-01 15:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_companies', '0004_auto_20180430_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='added',
            field=models.DateField(db_column='Added', default=datetime.date.today, help_text='Date this company was added.', verbose_name='Date added'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address1',
            field=models.CharField(blank=True, db_column='Address1', max_length=200, null=True, verbose_name='Address (line 1)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address2',
            field=models.CharField(blank=True, db_column='Address2', max_length=200, null=True, verbose_name='Address (line 2)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='alpha',
            field=models.CharField(blank=True, db_column='Alpha', help_text='The alphabetical sorting name used for this company.', max_length=200, null=True, verbose_name='Sort name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='annualmeet',
            field=models.CharField(blank=True, db_column='AnnualMeet', help_text='About the annual meeting.', max_length=30, null=True, verbose_name='Annual meeting'),
        ),
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.CharField(blank=True, db_column='Category', help_text='Industry category; (so far) mostly used for non-profit companies.', max_length=200, null=True, verbose_name='Industry category'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, db_column='City', help_text='City for address.', max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='company',
            name='class_field',
            field=models.CharField(blank=True, db_column='Class', help_text='An integer describing the class of the company.  (Unknown what this is)', max_length=10, null=True, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='company',
            name='coid',
            field=models.CharField(db_column='COID', help_text='Alphanumeric unique identifier for each company.', max_length=100, primary_key=True, serialize=False, verbose_name='Company ID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='companytype',
            field=models.CharField(blank=True, db_column='CompanyType', help_text='General type of company.  This is an unstandardized field.', max_length=40, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact',
            field=models.CharField(blank=True, db_column='Contact', help_text='Name of main contact person.', max_length=200, null=True, verbose_name='Contact person'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contactemail',
            field=models.CharField(blank=True, db_column='ContactEmail', help_text='Email address of main contact person.', max_length=200, null=True, verbose_name='Contact email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contactphone',
            field=models.CharField(blank=True, db_column='ContactPhone', help_text='Phone number of main contact person.', max_length=30, null=True, verbose_name='Contact phone'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, db_column='Description', help_text='Full description of company.', null=True, verbose_name='Company description'),
        ),
        migrations.AlterField(
            model_name='company',
            name='enteredby',
            field=models.CharField(blank=True, db_column='EnteredBy', help_text='Who was the staff person that last entered this data.', max_length=30, null=True, verbose_name='Data entered by'),
        ),
        migrations.AlterField(
            model_name='company',
            name='exchange',
            field=models.CharField(blank=True, db_column='Exchange', help_text='Primary exchange that the company is traded on.  This is an unstandardized field.', max_length=50, null=True, verbose_name='Stock exchange'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fax',
            field=models.CharField(blank=True, db_column='Fax', help_text='General fax number for company.', max_length=30, null=True, verbose_name='Fax number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='footnotes',
            field=models.TextField(blank=True, db_column='Footnotes', help_text='Any footnotes to be used in publication.', null=True, verbose_name='Footnotes'),
        ),
        migrations.AlterField(
            model_name='company',
            name='founded',
            field=models.IntegerField(blank=True, db_column='Founded', help_text='Year company was founded.', null=True, verbose_name='Year founded'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fymonth',
            field=models.IntegerField(blank=True, db_column='FYMonth', help_text='The number month of the fiscal year end of the company.  Such as 1 for January.', null=True, verbose_name='Fiscal year end month'),
        ),
        migrations.AlterField(
            model_name='company',
            name='inc',
            field=models.IntegerField(blank=True, db_column='Inc', help_text='Year company was incorporated.', null=True, verbose_name='Year incorporated'),
        ),
        migrations.AlterField(
            model_name='company',
            name='incst',
            field=models.CharField(blank=True, db_column='IncSt', help_text='The state the company was incorporated in.  Please use the two character postal abbreviation, such as "MN".', max_length=2, null=True, verbose_name='State incorporated'),
        ),
        migrations.AlterField(
            model_name='company',
            name='irsno',
            field=models.CharField(blank=True, db_column='IRSNo', max_length=100, null=True, verbose_name='IRS number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, db_column='Company', help_text='Full, official name of company', max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='notes',
            field=models.TextField(blank=True, db_column='Notes', help_text='Any internal notes about this company.', null=True, verbose_name='Internal notes'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, db_column='Phone', help_text='General phone number for company (see Contact Phone for specific contact phone number).', max_length=30, null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='seealso',
            field=models.CharField(blank=True, db_column='SeeAlso', help_text='Descriptive reference for a related company.', max_length=100, null=True, verbose_name='See also'),
        ),
        migrations.AlterField(
            model_name='company',
            name='seealsoid',
            field=models.ForeignKey(blank=True, db_column='SeeAlsoID', help_text='The company ID to any related reference.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='business_companies.Company', verbose_name='See also company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='shortdesc',
            field=models.CharField(blank=True, db_column='ShortDesc', help_text='Short, one or two sentence, description of company.', max_length=750, null=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.CharField(blank=True, db_column='State', help_text='State for address; please use the postal abbreviation, such as "MN".', max_length=2, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='company',
            name='stocksymbol',
            field=models.CharField(blank=True, db_column='StockSymbol', help_text='Stock symbol used on exchanges.', max_length=12, null=True, verbose_name='Stock symbol'),
        ),
        migrations.AlterField(
            model_name='company',
            name='www',
            field=models.CharField(blank=True, db_column='WWW', help_text='URL of website for company.', max_length=200, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='company',
            name='zip',
            field=models.CharField(blank=True, db_column='Zip', help_text='Zipcode for address.', max_length=20, null=True, verbose_name='Zipcode'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='added',
            field=models.DateField(db_column='Added', default=datetime.date.today, help_text='Date this company was added.', verbose_name='Date added'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='address1',
            field=models.CharField(blank=True, db_column='Address1', max_length=200, null=True, verbose_name='Address (line 1)'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='address2',
            field=models.CharField(blank=True, db_column='Address2', max_length=200, null=True, verbose_name='Address (line 2)'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='alpha',
            field=models.CharField(blank=True, db_column='Alpha', help_text='The alphabetical sorting name used for this company.', max_length=200, null=True, verbose_name='Sort name'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='annualmeet',
            field=models.CharField(blank=True, db_column='AnnualMeet', help_text='About the annual meeting.', max_length=30, null=True, verbose_name='Annual meeting'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='category',
            field=models.CharField(blank=True, db_column='Category', help_text='Industry category; (so far) mostly used for non-profit companies.', max_length=200, null=True, verbose_name='Industry category'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='city',
            field=models.CharField(blank=True, db_column='City', help_text='City for address.', max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='class_field',
            field=models.CharField(blank=True, db_column='Class', help_text='An integer describing the class of the company.  (Unknown what this is)', max_length=10, null=True, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='coid',
            field=models.CharField(db_column='COID', db_index=True, help_text='Alphanumeric unique identifier for each company.', max_length=100, verbose_name='Company ID'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='companytype',
            field=models.CharField(blank=True, db_column='CompanyType', help_text='General type of company.  This is an unstandardized field.', max_length=40, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='contact',
            field=models.CharField(blank=True, db_column='Contact', help_text='Name of main contact person.', max_length=200, null=True, verbose_name='Contact person'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='contactemail',
            field=models.CharField(blank=True, db_column='ContactEmail', help_text='Email address of main contact person.', max_length=200, null=True, verbose_name='Contact email'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='contactphone',
            field=models.CharField(blank=True, db_column='ContactPhone', help_text='Phone number of main contact person.', max_length=30, null=True, verbose_name='Contact phone'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='description',
            field=models.TextField(blank=True, db_column='Description', help_text='Full description of company.', null=True, verbose_name='Company description'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='enteredby',
            field=models.CharField(blank=True, db_column='EnteredBy', help_text='Who was the staff person that last entered this data.', max_length=30, null=True, verbose_name='Data entered by'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='exchange',
            field=models.CharField(blank=True, db_column='Exchange', help_text='Primary exchange that the company is traded on.  This is an unstandardized field.', max_length=50, null=True, verbose_name='Stock exchange'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='fax',
            field=models.CharField(blank=True, db_column='Fax', help_text='General fax number for company.', max_length=30, null=True, verbose_name='Fax number'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='footnotes',
            field=models.TextField(blank=True, db_column='Footnotes', help_text='Any footnotes to be used in publication.', null=True, verbose_name='Footnotes'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='founded',
            field=models.IntegerField(blank=True, db_column='Founded', help_text='Year company was founded.', null=True, verbose_name='Year founded'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='fymonth',
            field=models.IntegerField(blank=True, db_column='FYMonth', help_text='The number month of the fiscal year end of the company.  Such as 1 for January.', null=True, verbose_name='Fiscal year end month'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='inc',
            field=models.IntegerField(blank=True, db_column='Inc', help_text='Year company was incorporated.', null=True, verbose_name='Year incorporated'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='incst',
            field=models.CharField(blank=True, db_column='IncSt', help_text='The state the company was incorporated in.  Please use the two character postal abbreviation, such as "MN".', max_length=2, null=True, verbose_name='State incorporated'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='irsno',
            field=models.CharField(blank=True, db_column='IRSNo', max_length=100, null=True, verbose_name='IRS number'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='name',
            field=models.CharField(blank=True, db_column='Company', help_text='Full, official name of company', max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='notes',
            field=models.TextField(blank=True, db_column='Notes', help_text='Any internal notes about this company.', null=True, verbose_name='Internal notes'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='phone',
            field=models.CharField(blank=True, db_column='Phone', help_text='General phone number for company (see Contact Phone for specific contact phone number).', max_length=30, null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='seealso',
            field=models.CharField(blank=True, db_column='SeeAlso', help_text='Descriptive reference for a related company.', max_length=100, null=True, verbose_name='See also'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='shortdesc',
            field=models.CharField(blank=True, db_column='ShortDesc', help_text='Short, one or two sentence, description of company.', max_length=750, null=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='state',
            field=models.CharField(blank=True, db_column='State', help_text='State for address; please use the postal abbreviation, such as "MN".', max_length=2, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='stocksymbol',
            field=models.CharField(blank=True, db_column='StockSymbol', help_text='Stock symbol used on exchanges.', max_length=12, null=True, verbose_name='Stock symbol'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='www',
            field=models.CharField(blank=True, db_column='WWW', help_text='URL of website for company.', max_length=200, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='zip',
            field=models.CharField(blank=True, db_column='Zip', help_text='Zipcode for address.', max_length=20, null=True, verbose_name='Zipcode'),
        ),
    ]
