# Generated by Django 2.0.4 on 2018-05-01 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_companies', '0005_auto_20180501_1049'),
    ]

    operations = [
        migrations.RenameField(
            'company',
            'history',
            'companyhistory'
        ),
    ]
