# Generated by Django 2.0.4 on 2018-05-01 19:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_companies', '0005_auto_20180501_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'managed': True, 'ordering': ['name'], 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='employees',
            options={'managed': True, 'ordering': ['-publishyear', '-added', 'coid__name'], 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterField(
            model_name='company',
            name='companyhistory',
            field=models.TextField(blank=True, db_column='CompanyHistory', help_text='Descriptive history of company.', null=True, verbose_name='Descriptive history'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='added',
            field=models.DateField(db_column='Added', default=datetime.date.today, help_text='The date this information was added.', verbose_name='Date added'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='coid',
            field=models.ForeignKey(db_column='COID', help_text='The associated company with this data.', on_delete=django.db.models.deletion.DO_NOTHING, to='business_companies.Company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='footnotes',
            field=models.TextField(blank=True, db_column='Footnotes', help_text='Any footnotes to be used in publication.', null=True, verbose_name='Footnotes'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='fulltime',
            field=models.IntegerField(blank=True, db_column='FullTime', help_text='Number of full-time employees', null=True, verbose_name='Full time'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='id',
            field=models.AutoField(db_column='ID', help_text='This is an auto incrementing ID that should not need to be manually created or updated.', primary_key=True, serialize=False, verbose_name='Employees ID'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='minnesota',
            field=models.IntegerField(blank=True, db_column='Minnesota', help_text='Number of employees in Minnesota', null=True, verbose_name='MN employees'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='notes',
            field=models.TextField(blank=True, db_column='Notes', help_text='Any internal notes about this company.', null=True, verbose_name='Internal notes'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='parttime',
            field=models.IntegerField(blank=True, db_column='PartTime', help_text='Number of part-time employees', null=True, verbose_name='Part-time'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='publishyear',
            field=models.IntegerField(db_column='PublishYear', default=2018, help_text='The calendar year this data will be published.', verbose_name='Publish year'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='total',
            field=models.IntegerField(blank=True, db_column='Total', help_text='Total number of all employees.  This is the main number used in publication.', null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='union',
            field=models.IntegerField(blank=True, db_column='Union', help_text='Number of union employees', null=True, verbose_name='Union'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='companyhistory',
            field=models.TextField(blank=True, db_column='CompanyHistory', help_text='Descriptive history of company.', null=True, verbose_name='Descriptive history'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='added',
            field=models.DateField(db_column='Added', default=datetime.date.today, help_text='The date this information was added.', verbose_name='Date added'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='footnotes',
            field=models.TextField(blank=True, db_column='Footnotes', help_text='Any footnotes to be used in publication.', null=True, verbose_name='Footnotes'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='fulltime',
            field=models.IntegerField(blank=True, db_column='FullTime', help_text='Number of full-time employees', null=True, verbose_name='Full time'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='id',
            field=models.IntegerField(blank=True, db_column='ID', db_index=True, help_text='This is an auto incrementing ID that should not need to be manually created or updated.', verbose_name='Employees ID'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='minnesota',
            field=models.IntegerField(blank=True, db_column='Minnesota', help_text='Number of employees in Minnesota', null=True, verbose_name='MN employees'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='notes',
            field=models.TextField(blank=True, db_column='Notes', help_text='Any internal notes about this company.', null=True, verbose_name='Internal notes'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='parttime',
            field=models.IntegerField(blank=True, db_column='PartTime', help_text='Number of part-time employees', null=True, verbose_name='Part-time'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='publishyear',
            field=models.IntegerField(db_column='PublishYear', default=2018, help_text='The calendar year this data will be published.', verbose_name='Publish year'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='total',
            field=models.IntegerField(blank=True, db_column='Total', help_text='Total number of all employees.  This is the main number used in publication.', null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='union',
            field=models.IntegerField(blank=True, db_column='Union', help_text='Number of union employees', null=True, verbose_name='Union'),
        ),
    ]
