# Generated by Django 2.0.4 on 2018-05-01 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_companies', '0006_auto_20180501_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finances',
            options={'managed': True, 'ordering': ['-publishyear', '-revenue', 'coid__name'], 'verbose_name_plural': 'Finances'},
        ),
        migrations.AlterField(
            model_name='finances',
            name='ati',
            field=models.FloatField(blank=True, db_column='ATI', help_text='Unsure?.', null=True, verbose_name='ATI'),
        ),
        migrations.AlterField(
            model_name='finances',
            name='category',
            field=models.CharField(blank=True, db_column='Category', help_text='(Not needed, see Company tables) Industry category of company.', max_length=300, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='finances',
            name='ceo',
            field=models.CharField(blank=True, db_column='CEO', help_text='(Not needed, see Officers tables) CEO of the year.', max_length=300, null=True, verbose_name='CEO'),
        ),
        migrations.AlterField(
            model_name='finances',
            name='coid',
            field=models.ForeignKey(db_column='COID', help_text='Company associated with this record.', on_delete=django.db.models.deletion.CASCADE, to='business_companies.Company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='finances',
            name='customrank',
            field=models.IntegerField(blank=True, db_column='CustomRank', help_text='(Not needed) Override ranking by revenue or other number.', null=True, verbose_name='Custom rank'),
        ),
        migrations.AlterField(
            model_name='finances',
            name='customrankassets',
            field=models.IntegerField(blank=True, db_column='CustomRankAssets', help_text='(Not needed, see previous rows of data)', null=True),
        ),
        migrations.AlterField(
            model_name='finances',
            name='customrankblend',
            field=models.IntegerField(blank=True, db_column='CustomRankBlend', help_text='(Not needed, see previous rows of data)', null=True),
        ),
        migrations.AlterField(
            model_name='finances',
            name='customrankmarketcap',
            field=models.IntegerField(blank=True, db_column='CustomRankMarketCap', help_text='(Not needed, see previous rows of data)', null=True),
        ),
        migrations.AlterField(
            model_name='finances',
            name='customrankprofit',
            field=models.IntegerField(blank=True, db_column='CustomRankProfit', help_text='(Not needed, see previous rows of data)', null=True),
        ),
        migrations.AlterField(
            model_name='finances',
            name='customrankrevenue',
            field=models.IntegerField(blank=True, db_column='CustomRankRevenue', help_text='(Not needed, see previous rows of data)', null=True),
        ),
        migrations.AlterField(
            model_name='finances',
            name='debt',
            field=models.FloatField(blank=True, db_column='Debt', null=True, verbose_name='Debt'),
        ),
        migrations.AlterField(
            model_name='finances',
            name='done',
            field=models.CharField(blank=True, db_column='Done', help_text='(Not needed) Done for the year.', max_length=10, null=True, verbose_name='Done'),
        ),
        migrations.AlterField(
            model_name='finances',
            name='earningspershare',
            field=models.FloatField(blank=True, db_column='EarningsPerShare', null=True, verbose_name='Earnings per share'),
        ),
        migrations.AlterField(
            model_name='finances',
            name='empdate',
            field=models.DateField(blank=True, db_column='EMPDate', help_text='(Not needed, see Employees tables) Date total employees was recorded.', null=True, verbose_name='Total employees date'),
        ),
        migrations.AlterField(
            model_name='finances',
            name='footnotes',
            field=models.TextField(blank=True, db_column='Footnotes', help_text='Any footnotes to be used in publication.', null=True, verbose_name='Footnotes'),
        ),
        migrations.AlterField(
            model_name='finances',
            name='fye',
            field=models.DateField(blank=True, db_column='FYE', help_text='(Not needed?  See maxoffye) Fiscal year end.', null=True, verbose_name='Fiscal year end'),
        ),
        migrations.AlterField(
            model_name='finances',
            name='id',
            field=models.AutoField(db_column='ID', help_text='This is an auto incrementing ID that should not need to be manually created or updated.', primary_key=True, serialize=False, verbose_name='Financials ID'),
        ),
        migrations.AlterField(
            model_name='finances',
            name='marketcap',
            field=models.FloatField(blank=True, db_column='MarketCap', null=True, verbose_name='Market cap'),
        ),
        migrations.AlterField(
            model_name='finances',
            name='maxoffye',
            field=models.DateField(blank=True, db_column='MaxOfFYE', help_text='Fiscal year end for the financial data.', null=True, verbose_name='Fiscal year end'),
        ),
        migrations.AlterField(
            model_name='finances',
            name='mnemployees',
            field=models.IntegerField(blank=True, db_column='MNEmployees', help_text='(Not needed, see Employees tables) Number of total employees in Minnesota.', null=True, verbose_name='MN employees'),
        ),
        migrations.AlterField(
            model_name='finances',
            name='netincome',
            field=models.FloatField(blank=True, db_column='NetIncome', null=True, verbose_name='Net income'),
        ),
        migrations.AlterField(
            model_name='finances',
            name='notes',
            field=models.TextField(blank=True, db_column='Notes', help_text='Any internal notes about this company.', null=True, verbose_name='Internal notes'),
        ),
        migrations.AlterField(
            model_name='finances',
            name='prevyearati',
            field=models.FloatField(blank=True, db_column='PrevYearATI', help_text='(Not needed, see previous rows of data)', null=True),
        ),
        migrations.AlterField(
            model_name='finances',
            name='prevyearclose',
            field=models.FloatField(blank=True, db_column='PrevYearClose', help_text='(Not needed, see previous rows of data)', null=True),
        ),
        migrations.AlterField(
            model_name='finances',
            name='prevyeardebt',
            field=models.FloatField(blank=True, db_column='PrevYearDebt', help_text='(Not needed, see previous rows of data)', null=True),
        ),
        migrations.AlterField(
            model_name='finances',
            name='prevyearearnpershare',
            field=models.FloatField(blank=True, db_column='PrevYearEarnPerShare', help_text='(Not needed, see previous rows of data)', null=True),
        ),
        migrations.AlterField(
            model_name='finances',
            name='prevyearfye',
            field=models.DateField(blank=True, db_column='PrevYearFYE', help_text='(Not needed, see previous rows of data)', null=True),
        ),
        migrations.AlterField(
            model_name='finances',
            name='prevyearmarketcap',
            field=models.FloatField(blank=True, db_column='PrevYearMarketCap', help_text='(Not needed, see previous rows of data)', null=True),
        ),
        migrations.AlterField(
            model_name='finances',
            name='prevyearmnemp',
            field=models.IntegerField(blank=True, db_column='PrevYearMNEmp', help_text='(Not needed, see previous rows of data)', null=True),
        ),
        migrations.AlterField(
            model_name='finances',
            name='prevyearnetincome',
            field=models.FloatField(blank=True, db_column='PrevYearNetIncome', help_text='(Not needed, see previous rows of data)', null=True),
        ),
        migrations.AlterField(
            model_name='finances',
            name='prevyearrevenue',
            field=models.FloatField(blank=True, db_column='PrevYearRevenue', help_text='(Not needed, see previous rows of data)', null=True),
        ),
        migrations.AlterField(
            model_name='finances',
            name='prevyearshareequity',
            field=models.FloatField(blank=True, db_column='PrevYearShareEquity', help_text='(Not needed, see previous rows of data)', null=True),
        ),
        migrations.AlterField(
            model_name='finances',
            name='prevyearshares',
            field=models.FloatField(blank=True, db_column='PrevYearShares', help_text='(Not needed, see previous rows of data)', null=True),
        ),
        migrations.AlterField(
            model_name='finances',
            name='prevyeartotalassets',
            field=models.FloatField(blank=True, db_column='PrevYearTotalAssets', help_text='(Not needed, see previous rows of data)', null=True),
        ),
        migrations.AlterField(
            model_name='finances',
            name='prevyeartotalemp',
            field=models.IntegerField(blank=True, db_column='PrevYearTotalEmp', help_text='(Not needed, see previous rows of data)', null=True),
        ),
        migrations.AlterField(
            model_name='finances',
            name='publishyear',
            field=models.IntegerField(db_column='PublishYear', default=2018, help_text='Year this data will be published.', verbose_name='Publish year'),
        ),
        migrations.AlterField(
            model_name='finances',
            name='revenue',
            field=models.FloatField(blank=True, db_column='Revenue', null=True, verbose_name='Revenue'),
        ),
        migrations.AlterField(
            model_name='finances',
            name='shareholdersequity',
            field=models.FloatField(blank=True, db_column='ShareholdersEquity', null=True, verbose_name='Shareholders equity'),
        ),
        migrations.AlterField(
            model_name='finances',
            name='shares',
            field=models.FloatField(blank=True, db_column='Shares', null=True, verbose_name='Number of shares'),
        ),
        migrations.AlterField(
            model_name='finances',
            name='totalassets',
            field=models.FloatField(blank=True, db_column='TotalAssets', null=True, verbose_name='Total assets'),
        ),
        migrations.AlterField(
            model_name='finances',
            name='totalemployees',
            field=models.IntegerField(blank=True, db_column='TotalEmployees', help_text='(Not needed, see Employees tables) Number of total employees.', null=True, verbose_name='Total employees'),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='ati',
            field=models.FloatField(blank=True, db_column='ATI', help_text='Unsure?.', null=True, verbose_name='ATI'),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='category',
            field=models.CharField(blank=True, db_column='Category', help_text='(Not needed, see Company tables) Industry category of company.', max_length=300, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='ceo',
            field=models.CharField(blank=True, db_column='CEO', help_text='(Not needed, see Officers tables) CEO of the year.', max_length=300, null=True, verbose_name='CEO'),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='customrank',
            field=models.IntegerField(blank=True, db_column='CustomRank', help_text='(Not needed) Override ranking by revenue or other number.', null=True, verbose_name='Custom rank'),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='customrankassets',
            field=models.IntegerField(blank=True, db_column='CustomRankAssets', help_text='(Not needed, see previous rows of data)', null=True),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='customrankblend',
            field=models.IntegerField(blank=True, db_column='CustomRankBlend', help_text='(Not needed, see previous rows of data)', null=True),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='customrankmarketcap',
            field=models.IntegerField(blank=True, db_column='CustomRankMarketCap', help_text='(Not needed, see previous rows of data)', null=True),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='customrankprofit',
            field=models.IntegerField(blank=True, db_column='CustomRankProfit', help_text='(Not needed, see previous rows of data)', null=True),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='customrankrevenue',
            field=models.IntegerField(blank=True, db_column='CustomRankRevenue', help_text='(Not needed, see previous rows of data)', null=True),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='debt',
            field=models.FloatField(blank=True, db_column='Debt', null=True, verbose_name='Debt'),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='done',
            field=models.CharField(blank=True, db_column='Done', help_text='(Not needed) Done for the year.', max_length=10, null=True, verbose_name='Done'),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='earningspershare',
            field=models.FloatField(blank=True, db_column='EarningsPerShare', null=True, verbose_name='Earnings per share'),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='empdate',
            field=models.DateField(blank=True, db_column='EMPDate', help_text='(Not needed, see Employees tables) Date total employees was recorded.', null=True, verbose_name='Total employees date'),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='footnotes',
            field=models.TextField(blank=True, db_column='Footnotes', help_text='Any footnotes to be used in publication.', null=True, verbose_name='Footnotes'),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='fye',
            field=models.DateField(blank=True, db_column='FYE', help_text='(Not needed?  See maxoffye) Fiscal year end.', null=True, verbose_name='Fiscal year end'),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='id',
            field=models.IntegerField(blank=True, db_column='ID', db_index=True, help_text='This is an auto incrementing ID that should not need to be manually created or updated.', verbose_name='Financials ID'),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='marketcap',
            field=models.FloatField(blank=True, db_column='MarketCap', null=True, verbose_name='Market cap'),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='maxoffye',
            field=models.DateField(blank=True, db_column='MaxOfFYE', help_text='Fiscal year end for the financial data.', null=True, verbose_name='Fiscal year end'),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='mnemployees',
            field=models.IntegerField(blank=True, db_column='MNEmployees', help_text='(Not needed, see Employees tables) Number of total employees in Minnesota.', null=True, verbose_name='MN employees'),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='netincome',
            field=models.FloatField(blank=True, db_column='NetIncome', null=True, verbose_name='Net income'),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='notes',
            field=models.TextField(blank=True, db_column='Notes', help_text='Any internal notes about this company.', null=True, verbose_name='Internal notes'),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='prevyearati',
            field=models.FloatField(blank=True, db_column='PrevYearATI', help_text='(Not needed, see previous rows of data)', null=True),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='prevyearclose',
            field=models.FloatField(blank=True, db_column='PrevYearClose', help_text='(Not needed, see previous rows of data)', null=True),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='prevyeardebt',
            field=models.FloatField(blank=True, db_column='PrevYearDebt', help_text='(Not needed, see previous rows of data)', null=True),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='prevyearearnpershare',
            field=models.FloatField(blank=True, db_column='PrevYearEarnPerShare', help_text='(Not needed, see previous rows of data)', null=True),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='prevyearfye',
            field=models.DateField(blank=True, db_column='PrevYearFYE', help_text='(Not needed, see previous rows of data)', null=True),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='prevyearmarketcap',
            field=models.FloatField(blank=True, db_column='PrevYearMarketCap', help_text='(Not needed, see previous rows of data)', null=True),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='prevyearmnemp',
            field=models.IntegerField(blank=True, db_column='PrevYearMNEmp', help_text='(Not needed, see previous rows of data)', null=True),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='prevyearnetincome',
            field=models.FloatField(blank=True, db_column='PrevYearNetIncome', help_text='(Not needed, see previous rows of data)', null=True),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='prevyearrevenue',
            field=models.FloatField(blank=True, db_column='PrevYearRevenue', help_text='(Not needed, see previous rows of data)', null=True),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='prevyearshareequity',
            field=models.FloatField(blank=True, db_column='PrevYearShareEquity', help_text='(Not needed, see previous rows of data)', null=True),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='prevyearshares',
            field=models.FloatField(blank=True, db_column='PrevYearShares', help_text='(Not needed, see previous rows of data)', null=True),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='prevyeartotalassets',
            field=models.FloatField(blank=True, db_column='PrevYearTotalAssets', help_text='(Not needed, see previous rows of data)', null=True),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='prevyeartotalemp',
            field=models.IntegerField(blank=True, db_column='PrevYearTotalEmp', help_text='(Not needed, see previous rows of data)', null=True),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='publishyear',
            field=models.IntegerField(db_column='PublishYear', default=2018, help_text='Year this data will be published.', verbose_name='Publish year'),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='revenue',
            field=models.FloatField(blank=True, db_column='Revenue', null=True, verbose_name='Revenue'),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='shareholdersequity',
            field=models.FloatField(blank=True, db_column='ShareholdersEquity', null=True, verbose_name='Shareholders equity'),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='shares',
            field=models.FloatField(blank=True, db_column='Shares', null=True, verbose_name='Number of shares'),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='totalassets',
            field=models.FloatField(blank=True, db_column='TotalAssets', null=True, verbose_name='Total assets'),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='totalemployees',
            field=models.IntegerField(blank=True, db_column='TotalEmployees', help_text='(Not needed, see Employees tables) Number of total employees.', null=True, verbose_name='Total employees'),
        ),
    ]
