# Generated by Django 2.0.4 on 2018-05-03 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_companies', '0009_auto_20180503_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officersalary',
            options={'managed': True, 'ordering': ['-publishyear', 'officerid__coid__name', 'officerid__last'], 'verbose_name_plural': 'Officer Salaries'},
        ),
    ]
