# Generated by Django 2.0.5 on 2018-05-09 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_companies', '0011_auto_20180503_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='finances',
            name='netincomebeforeextra',
            field=models.FloatField(
                blank=True,
                db_column='NetIncomeBeforeExtra',
                null=True,
                verbose_name='Net income before extraordinary items'),
        ),
        migrations.AddField(
            model_name='finances',
            name='prevyearnetincomebeforeextra',
            field=models.FloatField(
                blank=True,
                db_column='PrevYearNetIncomeBE',
                help_text='(Not needed, see previous rows of data)',
                null=True,
                verbose_name=
                'Previous year: Net income before extraordinary items'),
        ),
        migrations.AddField(
            model_name='historicalfinances',
            name='netincomebeforeextra',
            field=models.FloatField(
                blank=True,
                db_column='NetIncomeBeforeExtra',
                null=True,
                verbose_name='Net income before extraordinary items'),
        ),
        migrations.AddField(
            model_name='historicalfinances',
            name='prevyearnetincomebeforeextra',
            field=models.FloatField(
                blank=True,
                db_column='PrevYearNetIncomeBE',
                help_text='(Not needed, see previous rows of data)',
                null=True,
                verbose_name=
                'Previous year: Net income before extraordinary items'),
        ),
    ]
