# Generated by Django 2.0.5 on 2018-05-11 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_companies', '0012_auto_20180509_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='The date this record was created.', null=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='company',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, help_text='The date this record was last modified.', null=True, verbose_name='Modified date'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='The date this record was created.', null=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, help_text='The date this record was last modified.', null=True, verbose_name='Modified date'),
        ),
        migrations.AlterField(
            model_name='finances',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='The date this record was created.', null=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='finances',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, help_text='The date this record was last modified.', null=True, verbose_name='Modified date'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False, help_text='The date this record was created.', null=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, help_text='The date this record was last modified.', null=True, verbose_name='Modified date'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False, help_text='The date this record was created.', null=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, help_text='The date this record was last modified.', null=True, verbose_name='Modified date'),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False, help_text='The date this record was created.', null=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, help_text='The date this record was last modified.', null=True, verbose_name='Modified date'),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitfinances',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False, help_text='The date this record was created.', null=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitfinances',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, help_text='The date this record was last modified.', null=True, verbose_name='Modified date'),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitsalary',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False, help_text='The date this record was created.', null=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitsalary',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, help_text='The date this record was last modified.', null=True, verbose_name='Modified date'),
        ),
        migrations.AlterField(
            model_name='historicalofficer',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False, help_text='The date this record was created.', null=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='historicalofficer',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, help_text='The date this record was last modified.', null=True, verbose_name='Modified date'),
        ),
        migrations.AlterField(
            model_name='historicalofficer',
            name='title',
            field=models.CharField(blank=True, db_column='Title', help_text='The current title of the officer.  Titls should be managed in the Office Salary table, so that changes to the title can be tracked.', max_length=110, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='historicalofficersalary',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False, help_text='The date this record was created.', null=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='historicalofficersalary',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, help_text='The date this record was last modified.', null=True, verbose_name='Modified date'),
        ),
        migrations.AlterField(
            model_name='historicalofficersalary',
            name='title',
            field=models.CharField(blank=True, db_column='Title', help_text='Title of the officer for this year.', max_length=100, null=True, verbose_name='Officer title'),
        ),
        migrations.AlterField(
            model_name='nonprofitfinances',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='The date this record was created.', null=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='nonprofitfinances',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, help_text='The date this record was last modified.', null=True, verbose_name='Modified date'),
        ),
        migrations.AlterField(
            model_name='nonprofitsalary',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='The date this record was created.', null=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='nonprofitsalary',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, help_text='The date this record was last modified.', null=True, verbose_name='Modified date'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='The date this record was created.', null=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, help_text='The date this record was last modified.', null=True, verbose_name='Modified date'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='title',
            field=models.CharField(blank=True, db_column='Title', help_text='The current title of the officer.  Titls should be managed in the Office Salary table, so that changes to the title can be tracked.', max_length=110, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='officersalary',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='The date this record was created.', null=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='officersalary',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, help_text='The date this record was last modified.', null=True, verbose_name='Modified date'),
        ),
        migrations.AlterField(
            model_name='officersalary',
            name='title',
            field=models.CharField(blank=True, db_column='Title', help_text='Title of the officer for this year.', max_length=100, null=True, verbose_name='Officer title'),
        ),
    ]
