# Generated by Django 2.0.5 on 2018-05-15 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_companies', '0013_auto_20180511_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalofficersalary',
            name='allothertotal',
            field=models.FloatField(blank=True, db_column='AllOtherTotal', help_text='All other compensation (perquisites)', null=True, verbose_name='All other total'),
        ),
        migrations.AlterField(
            model_name='historicalofficersalary',
            name='bonus',
            field=models.FloatField(blank=True, db_column='Bonus', help_text='Discretionary bonus; not performance related', null=True, verbose_name='Bonus'),
        ),
        migrations.AlterField(
            model_name='historicalofficersalary',
            name='ceopayratio',
            field=models.FloatField(blank=True, db_column='CEOPayRatio', help_text='Ratio of CEO to median employee pay (uses total in proxy Total LT equity SCT).', null=True, verbose_name='CEO pay ratio'),
        ),
        migrations.AlterField(
            model_name='historicalofficersalary',
            name='medianemployeepay',
            field=models.FloatField(blank=True, db_column='MedianEmployeePay', help_text='Pay of the median employee as disclosed in the proxy.', null=True, verbose_name='Median employee pay'),
        ),
        migrations.AlterField(
            model_name='historicalofficersalary',
            name='nonequityipc',
            field=models.FloatField(blank=True, db_column='NonEquityIPC', help_text='Non-equity incentive plan compensation (performance bonus).', null=True, verbose_name='Non-equity IPC'),
        ),
        migrations.AlterField(
            model_name='historicalofficersalary',
            name='optionaward',
            field=models.FloatField(blank=True, db_column='OptionAward', help_text='Value of new stock options granted', null=True, verbose_name='Option awards'),
        ),
        migrations.AlterField(
            model_name='historicalofficersalary',
            name='pensionchange',
            field=models.FloatField(blank=True, db_column='PensionChange', help_text='Change in pension value and nonqualified deferred compensation (an actuarial value of pension benefits; non-cash).', null=True, verbose_name='Pension change'),
        ),
        migrations.AlterField(
            model_name='historicalofficersalary',
            name='salary',
            field=models.FloatField(blank=True, db_column='Salary', help_text='Base annual salary for officer.', null=True, verbose_name='Base salary'),
        ),
        migrations.AlterField(
            model_name='historicalofficersalary',
            name='sayonpay',
            field=models.FloatField(blank=True, db_column='SayOnPay', help_text='Results of say on pay vote; comes at the annual meeting several weeks later.', null=True, verbose_name='Say on pay'),
        ),
        migrations.AlterField(
            model_name='historicalofficersalary',
            name='sharesvesting',
            field=models.FloatField(blank=True, db_column='SharesVesting', help_text='Value of restricted stock that vested during the year.', null=True, verbose_name='Shares vesting'),
        ),
        migrations.AlterField(
            model_name='historicalofficersalary',
            name='stockaward',
            field=models.FloatField(blank=True, db_column='StockAward', help_text='Value of new restricted stock awarded.', null=True, verbose_name='Stock awards'),
        ),
        migrations.AlterField(
            model_name='historicalofficersalary',
            name='stockchange',
            field=models.FloatField(blank=True, db_column='StockChange', help_text='Total return of stock during the fiscal year.', null=True, verbose_name='Stock change'),
        ),
        migrations.AlterField(
            model_name='historicalofficersalary',
            name='stockexpense',
            field=models.FloatField(blank=True, db_column='StockExpense', help_text='Value of options exercised during the year.', null=True, verbose_name='Stock expenses'),
        ),
        migrations.AlterField(
            model_name='historicalofficersalary',
            name='stockoptions',
            field=models.FloatField(blank=True, db_column='StockOptions', help_text='number of new stock options granted.', null=True, verbose_name='Stock options'),
        ),
        migrations.AlterField(
            model_name='historicalofficersalary',
            name='stockoptionsvalue',
            field=models.FloatField(blank=True, db_column='StockOptionsValue', help_text='Value of new stock options granted.', null=True, verbose_name='Value of stock options'),
        ),
        migrations.AlterField(
            model_name='historicalofficersalary',
            name='totalltequitysct',
            field=models.FloatField(blank=True, db_column='TotalLTEquitySCT', help_text='Total compensation as listed in summary compensation table (not our total).', null=True, verbose_name='Total LT equity SCT'),
        ),
        migrations.AlterField(
            model_name='officersalary',
            name='allothertotal',
            field=models.FloatField(blank=True, db_column='AllOtherTotal', help_text='All other compensation (perquisites)', null=True, verbose_name='All other total'),
        ),
        migrations.AlterField(
            model_name='officersalary',
            name='bonus',
            field=models.FloatField(blank=True, db_column='Bonus', help_text='Discretionary bonus; not performance related', null=True, verbose_name='Bonus'),
        ),
        migrations.AlterField(
            model_name='officersalary',
            name='ceopayratio',
            field=models.FloatField(blank=True, db_column='CEOPayRatio', help_text='Ratio of CEO to median employee pay (uses total in proxy Total LT equity SCT).', null=True, verbose_name='CEO pay ratio'),
        ),
        migrations.AlterField(
            model_name='officersalary',
            name='medianemployeepay',
            field=models.FloatField(blank=True, db_column='MedianEmployeePay', help_text='Pay of the median employee as disclosed in the proxy.', null=True, verbose_name='Median employee pay'),
        ),
        migrations.AlterField(
            model_name='officersalary',
            name='nonequityipc',
            field=models.FloatField(blank=True, db_column='NonEquityIPC', help_text='Non-equity incentive plan compensation (performance bonus).', null=True, verbose_name='Non-equity IPC'),
        ),
        migrations.AlterField(
            model_name='officersalary',
            name='optionaward',
            field=models.FloatField(blank=True, db_column='OptionAward', help_text='Value of new stock options granted', null=True, verbose_name='Option awards'),
        ),
        migrations.AlterField(
            model_name='officersalary',
            name='pensionchange',
            field=models.FloatField(blank=True, db_column='PensionChange', help_text='Change in pension value and nonqualified deferred compensation (an actuarial value of pension benefits; non-cash).', null=True, verbose_name='Pension change'),
        ),
        migrations.AlterField(
            model_name='officersalary',
            name='salary',
            field=models.FloatField(blank=True, db_column='Salary', help_text='Base annual salary for officer.', null=True, verbose_name='Base salary'),
        ),
        migrations.AlterField(
            model_name='officersalary',
            name='sayonpay',
            field=models.FloatField(blank=True, db_column='SayOnPay', help_text='Results of say on pay vote; comes at the annual meeting several weeks later.', null=True, verbose_name='Say on pay'),
        ),
        migrations.AlterField(
            model_name='officersalary',
            name='sharesvesting',
            field=models.FloatField(blank=True, db_column='SharesVesting', help_text='Value of restricted stock that vested during the year.', null=True, verbose_name='Shares vesting'),
        ),
        migrations.AlterField(
            model_name='officersalary',
            name='stockaward',
            field=models.FloatField(blank=True, db_column='StockAward', help_text='Value of new restricted stock awarded.', null=True, verbose_name='Stock awards'),
        ),
        migrations.AlterField(
            model_name='officersalary',
            name='stockchange',
            field=models.FloatField(blank=True, db_column='StockChange', help_text='Total return of stock during the fiscal year.', null=True, verbose_name='Stock change'),
        ),
        migrations.AlterField(
            model_name='officersalary',
            name='stockexpense',
            field=models.FloatField(blank=True, db_column='StockExpense', help_text='Value of options exercised during the year.', null=True, verbose_name='Stock expenses'),
        ),
        migrations.AlterField(
            model_name='officersalary',
            name='stockoptions',
            field=models.FloatField(blank=True, db_column='StockOptions', help_text='number of new stock options granted.', null=True, verbose_name='Stock options'),
        ),
        migrations.AlterField(
            model_name='officersalary',
            name='stockoptionsvalue',
            field=models.FloatField(blank=True, db_column='StockOptionsValue', help_text='Value of new stock options granted.', null=True, verbose_name='Value of stock options'),
        ),
        migrations.AlterField(
            model_name='officersalary',
            name='totalltequitysct',
            field=models.FloatField(blank=True, db_column='TotalLTEquitySCT', help_text='Total compensation as listed in summary compensation table (not our total).', null=True, verbose_name='Total LT equity SCT'),
        ),
    ]
