# Generated by Django 2.0.5 on 2018-06-11 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_companies', '0015_auto_20180517_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finances',
            name='customrank',
            field=models.IntegerField(
                blank=True,
                db_column='CustomRank',
                help_text=
                'Override the default ranking for the year, which is usually by revenue.  Overall, this is helpful for previous years, as data will can get updated and companies move in and out of the state.',
                null=True,
                verbose_name='Custom rank'),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='customrank',
            field=models.IntegerField(
                blank=True,
                db_column='CustomRank',
                help_text=
                'Override the default ranking for the year, which is usually by revenue.  Overall, this is helpful for previous years, as data will can get updated and companies move in and out of the state.',
                null=True,
                verbose_name='Custom rank'),
        )
    ]
