# Generated by Django 2.1.1 on 2018-09-18 18:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_companies', '0016_auto_20180611_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nonprofitfinances',
            options={'managed': True, 'ordering': ['-publishyear', '-revenue'], 'verbose_name_plural': 'NonProfit Finances'},
        ),
        migrations.AlterField(
            model_name='historicalnonprofitfinances',
            name='added',
            field=models.DateField(db_column='Added', default=datetime.date.today, help_text='Date when this record was added.', verbose_name='Added'),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitfinances',
            name='annualreportdate',
            field=models.DateField(db_column='AnnualReportDate', help_text='The date of the annual report.', verbose_name='Annual report date'),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitfinances',
            name='contribgrants',
            field=models.FloatField(blank=True, db_column='ContribGrants', help_text='The dollar amount of contributions and grants.', null=True, verbose_name='Contributions and grants'),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitfinances',
            name='eoybalance',
            field=models.FloatField(blank=True, db_column='EOYBalance', null=True, verbose_name='End of year balance'),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitfinances',
            name='excess',
            field=models.FloatField(blank=True, db_column='Excess', help_text='(needs description)', null=True, verbose_name='Excess'),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitfinances',
            name='expenses',
            field=models.FloatField(blank=True, db_column='Expenses', null=True, verbose_name='Expenses'),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitfinances',
            name='fiscalyearend',
            field=models.DateField(db_column='FiscalYearEnd', help_text='The date of the fiscal year end.', verbose_name='Fiscal year end'),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitfinances',
            name='footnotes',
            field=models.TextField(blank=True, db_column='Footnotes', help_text='Any footnotes to be used in publication.', null=True, verbose_name='Footnotes'),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitfinances',
            name='fundraisingexpenses',
            field=models.FloatField(blank=True, db_column='FundraisingExpenses', help_text='The dollar amount of expenses specifically from fundraising.', null=True, verbose_name='Fundraising expenses'),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitfinances',
            name='id',
            field=models.IntegerField(blank=True, db_column='ID', db_index=True, help_text='This is an auto incrementing ID that should not need to be manually created or updated.', verbose_name='Nonprofit Finances ID'),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitfinances',
            name='inputsource',
            field=models.CharField(blank=True, db_column='InputSource', help_text='how this data was entered, specifically if it was done through an import process.', max_length=512, null=True, verbose_name='Input source'),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitfinances',
            name='investgainslosses',
            field=models.FloatField(blank=True, db_column='InvestGainsLosses', null=True, verbose_name='Investment gains and losses'),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitfinances',
            name='managementgeneralexpenses',
            field=models.FloatField(blank=True, db_column='ManagementGeneralExpenses', help_text='The dollar amount of expenses specifically from management and general operating.', null=True, verbose_name='Management and general expenses'),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitfinances',
            name='notes',
            field=models.TextField(blank=True, db_column='Notes', help_text='Any notes used for internal purposes.', null=True, verbose_name='Internal notes'),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitfinances',
            name='programserviceexpense',
            field=models.FloatField(blank=True, db_column='ProgramServiceExpense', help_text='The dollar amount of expenses specifically from programs and service.', null=True, verbose_name='Programs and service expenses'),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitfinances',
            name='programservicerevenue',
            field=models.FloatField(blank=True, db_column='ProgramServiceRevenue', help_text='The dollar amount of revenue specifically from programs and service.', null=True, verbose_name='Programs and service revenue'),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitfinances',
            name='publishyear',
            field=models.IntegerField(db_column='PublishYear', help_text='Year this record is used for publishing.', verbose_name='Publish year'),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitfinances',
            name='revenue',
            field=models.FloatField(blank=True, db_column='Revenue', null=True, verbose_name='Revenue'),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitfinances',
            name='source',
            field=models.CharField(blank=True, db_column='Source', help_text='The source of the data, such as "IRS 990".', max_length=512, null=True, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitfinances',
            name='status',
            field=models.CharField(blank=True, db_column='Status', help_text='Describes status (unsure?).', max_length=50, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalofficersalary',
            name='ceo',
            field=models.IntegerField(blank=True, db_column='CEO', help_text='True (1) or False (0) on whether this officer is counted as CEO for this year.', null=True, verbose_name='Is CEO'),
        ),
        migrations.AlterField(
            model_name='nonprofitfinances',
            name='added',
            field=models.DateField(db_column='Added', default=datetime.date.today, help_text='Date when this record was added.', verbose_name='Added'),
        ),
        migrations.AlterField(
            model_name='nonprofitfinances',
            name='annualreportdate',
            field=models.DateField(db_column='AnnualReportDate', help_text='The date of the annual report.', verbose_name='Annual report date'),
        ),
        migrations.AlterField(
            model_name='nonprofitfinances',
            name='coid',
            field=models.ForeignKey(db_column='COID', help_text='Company associated with this record.', on_delete=django.db.models.deletion.CASCADE, to='business_companies.Company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='nonprofitfinances',
            name='contribgrants',
            field=models.FloatField(blank=True, db_column='ContribGrants', help_text='The dollar amount of contributions and grants.', null=True, verbose_name='Contributions and grants'),
        ),
        migrations.AlterField(
            model_name='nonprofitfinances',
            name='eoybalance',
            field=models.FloatField(blank=True, db_column='EOYBalance', null=True, verbose_name='End of year balance'),
        ),
        migrations.AlterField(
            model_name='nonprofitfinances',
            name='excess',
            field=models.FloatField(blank=True, db_column='Excess', help_text='(needs description)', null=True, verbose_name='Excess'),
        ),
        migrations.AlterField(
            model_name='nonprofitfinances',
            name='expenses',
            field=models.FloatField(blank=True, db_column='Expenses', null=True, verbose_name='Expenses'),
        ),
        migrations.AlterField(
            model_name='nonprofitfinances',
            name='fiscalyearend',
            field=models.DateField(db_column='FiscalYearEnd', help_text='The date of the fiscal year end.', verbose_name='Fiscal year end'),
        ),
        migrations.AlterField(
            model_name='nonprofitfinances',
            name='footnotes',
            field=models.TextField(blank=True, db_column='Footnotes', help_text='Any footnotes to be used in publication.', null=True, verbose_name='Footnotes'),
        ),
        migrations.AlterField(
            model_name='nonprofitfinances',
            name='fundraisingexpenses',
            field=models.FloatField(blank=True, db_column='FundraisingExpenses', help_text='The dollar amount of expenses specifically from fundraising.', null=True, verbose_name='Fundraising expenses'),
        ),
        migrations.AlterField(
            model_name='nonprofitfinances',
            name='id',
            field=models.AutoField(db_column='ID', help_text='This is an auto incrementing ID that should not need to be manually created or updated.', primary_key=True, serialize=False, verbose_name='Nonprofit Finances ID'),
        ),
        migrations.AlterField(
            model_name='nonprofitfinances',
            name='inputsource',
            field=models.CharField(blank=True, db_column='InputSource', help_text='how this data was entered, specifically if it was done through an import process.', max_length=512, null=True, verbose_name='Input source'),
        ),
        migrations.AlterField(
            model_name='nonprofitfinances',
            name='investgainslosses',
            field=models.FloatField(blank=True, db_column='InvestGainsLosses', null=True, verbose_name='Investment gains and losses'),
        ),
        migrations.AlterField(
            model_name='nonprofitfinances',
            name='managementgeneralexpenses',
            field=models.FloatField(blank=True, db_column='ManagementGeneralExpenses', help_text='The dollar amount of expenses specifically from management and general operating.', null=True, verbose_name='Management and general expenses'),
        ),
        migrations.AlterField(
            model_name='nonprofitfinances',
            name='notes',
            field=models.TextField(blank=True, db_column='Notes', help_text='Any notes used for internal purposes.', null=True, verbose_name='Internal notes'),
        ),
        migrations.AlterField(
            model_name='nonprofitfinances',
            name='programserviceexpense',
            field=models.FloatField(blank=True, db_column='ProgramServiceExpense', help_text='The dollar amount of expenses specifically from programs and service.', null=True, verbose_name='Programs and service expenses'),
        ),
        migrations.AlterField(
            model_name='nonprofitfinances',
            name='programservicerevenue',
            field=models.FloatField(blank=True, db_column='ProgramServiceRevenue', help_text='The dollar amount of revenue specifically from programs and service.', null=True, verbose_name='Programs and service revenue'),
        ),
        migrations.AlterField(
            model_name='nonprofitfinances',
            name='publishyear',
            field=models.IntegerField(db_column='PublishYear', help_text='Year this record is used for publishing.', verbose_name='Publish year'),
        ),
        migrations.AlterField(
            model_name='nonprofitfinances',
            name='revenue',
            field=models.FloatField(blank=True, db_column='Revenue', null=True, verbose_name='Revenue'),
        ),
        migrations.AlterField(
            model_name='nonprofitfinances',
            name='source',
            field=models.CharField(blank=True, db_column='Source', help_text='The source of the data, such as "IRS 990".', max_length=512, null=True, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='nonprofitfinances',
            name='status',
            field=models.CharField(blank=True, db_column='Status', help_text='Describes status (unsure?).', max_length=50, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='officersalary',
            name='ceo',
            field=models.IntegerField(blank=True, db_column='CEO', help_text='True (1) or False (0) on whether this officer is counted as CEO for this year.', null=True, verbose_name='Is CEO'),
        ),
    ]
