# Generated by Django 2.1.1 on 2018-09-18 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_companies', '0017_auto_20180918_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nonprofitsalary',
            options={'managed': True, 'ordering': ['-publishyear', '-total', 'officerid__last'], 'verbose_name_plural': 'NonProfit Salaries'},
        ),
        migrations.AddField(
            model_name='historicalnonprofitsalary',
            name='ceo',
            field=models.IntegerField(blank=True, db_column='CEO', help_text='True (1) or False (0) on whether this officer is counted as CEO for this year.', null=True, verbose_name='Is CEO'),
        ),
        migrations.AddField(
            model_name='historicalnonprofitsalary',
            name='title',
            field=models.CharField(blank=True, db_column='Title', help_text='Title of the officer for this year.', max_length=100, null=True, verbose_name='Officer title'),
        ),
        migrations.AddField(
            model_name='nonprofitsalary',
            name='ceo',
            field=models.IntegerField(blank=True, db_column='CEO', help_text='True (1) or False (0) on whether this officer is counted as CEO for this year.', null=True, verbose_name='Is CEO'),
        ),
        migrations.AddField(
            model_name='nonprofitsalary',
            name='title',
            field=models.CharField(blank=True, db_column='Title', help_text='Title of the officer for this year.', max_length=100, null=True, verbose_name='Officer title'),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitsalary',
            name='added',
            field=models.DateField(db_column='Added', help_text='Date when this record was added.', verbose_name='Added'),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitsalary',
            name='benefit',
            field=models.FloatField(blank=True, db_column='Benefit', help_text='Dollar value of benefits.', null=True, verbose_name='Benefits'),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitsalary',
            name='bonus',
            field=models.FloatField(blank=True, db_column='Bonus', null=True, verbose_name='Bonus'),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitsalary',
            name='deferred',
            field=models.FloatField(blank=True, db_column='Deferred', help_text='Any defferred compensation.', null=True, verbose_name='Deferred'),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitsalary',
            name='fiscalyearend',
            field=models.DateField(db_column='FiscalYearEnd', help_text='Fiscal year end date.', verbose_name='Fiscal year end'),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitsalary',
            name='fiscalyearnbr',
            field=models.IntegerField(blank=True, db_column='FiscalYearNBR', help_text='(unsure what used for?)', null=True, verbose_name='Fiscal Year NBR'),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitsalary',
            name='footnotes',
            field=models.TextField(blank=True, db_column='Footnotes', help_text='Any footnotes to be used in publication.', null=True, verbose_name='Footnotes'),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitsalary',
            name='id',
            field=models.IntegerField(blank=True, db_column='ID', db_index=True, help_text='This is an auto incrementing ID that should not need to be manually created or updated.', verbose_name='Nonprofit Salary ID'),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitsalary',
            name='notes',
            field=models.TextField(blank=True, db_column='Notes', help_text='Any notes used for internal purposes.', null=True, verbose_name='Internal notes'),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitsalary',
            name='other',
            field=models.FloatField(blank=True, db_column='Other', help_text='Other compensation.', null=True, verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitsalary',
            name='publishyear',
            field=models.IntegerField(db_column='PublishYear', help_text='Year this record is used for publishing.', verbose_name='Publish year'),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitsalary',
            name='salary',
            field=models.FloatField(blank=True, db_column='Salary', null=True, verbose_name='Base salary'),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitsalary',
            name='salarystatus',
            field=models.CharField(blank=True, db_column='SalaryStatus', help_text='Status of record (unsure what for?).', max_length=50, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitsalary',
            name='total',
            field=models.FloatField(blank=True, db_column='Total', help_text='This is manually entered and not calculated.', null=True, verbose_name='Total compensation'),
        ),
        migrations.AlterField(
            model_name='nonprofitsalary',
            name='added',
            field=models.DateField(db_column='Added', help_text='Date when this record was added.', verbose_name='Added'),
        ),
        migrations.AlterField(
            model_name='nonprofitsalary',
            name='benefit',
            field=models.FloatField(blank=True, db_column='Benefit', help_text='Dollar value of benefits.', null=True, verbose_name='Benefits'),
        ),
        migrations.AlterField(
            model_name='nonprofitsalary',
            name='bonus',
            field=models.FloatField(blank=True, db_column='Bonus', null=True, verbose_name='Bonus'),
        ),
        migrations.AlterField(
            model_name='nonprofitsalary',
            name='deferred',
            field=models.FloatField(blank=True, db_column='Deferred', help_text='Any defferred compensation.', null=True, verbose_name='Deferred'),
        ),
        migrations.AlterField(
            model_name='nonprofitsalary',
            name='fiscalyearend',
            field=models.DateField(db_column='FiscalYearEnd', help_text='Fiscal year end date.', verbose_name='Fiscal year end'),
        ),
        migrations.AlterField(
            model_name='nonprofitsalary',
            name='fiscalyearnbr',
            field=models.IntegerField(blank=True, db_column='FiscalYearNBR', help_text='(unsure what used for?)', null=True, verbose_name='Fiscal Year NBR'),
        ),
        migrations.AlterField(
            model_name='nonprofitsalary',
            name='footnotes',
            field=models.TextField(blank=True, db_column='Footnotes', help_text='Any footnotes to be used in publication.', null=True, verbose_name='Footnotes'),
        ),
        migrations.AlterField(
            model_name='nonprofitsalary',
            name='id',
            field=models.AutoField(db_column='ID', help_text='This is an auto incrementing ID that should not need to be manually created or updated.', primary_key=True, serialize=False, verbose_name='Nonprofit Salary ID'),
        ),
        migrations.AlterField(
            model_name='nonprofitsalary',
            name='notes',
            field=models.TextField(blank=True, db_column='Notes', help_text='Any notes used for internal purposes.', null=True, verbose_name='Internal notes'),
        ),
        migrations.AlterField(
            model_name='nonprofitsalary',
            name='officerid',
            field=models.ForeignKey(db_column='OfficerID', help_text='The officer that this data is for.', on_delete=django.db.models.deletion.CASCADE, to='business_companies.Officer', verbose_name='Officer ID'),
        ),
        migrations.AlterField(
            model_name='nonprofitsalary',
            name='other',
            field=models.FloatField(blank=True, db_column='Other', help_text='Other compensation.', null=True, verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='nonprofitsalary',
            name='publishyear',
            field=models.IntegerField(db_column='PublishYear', help_text='Year this record is used for publishing.', verbose_name='Publish year'),
        ),
        migrations.AlterField(
            model_name='nonprofitsalary',
            name='salary',
            field=models.FloatField(blank=True, db_column='Salary', null=True, verbose_name='Base salary'),
        ),
        migrations.AlterField(
            model_name='nonprofitsalary',
            name='salarystatus',
            field=models.CharField(blank=True, db_column='SalaryStatus', help_text='Status of record (unsure what for?).', max_length=50, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='nonprofitsalary',
            name='total',
            field=models.FloatField(blank=True, db_column='Total', help_text='This is manually entered and not calculated.', null=True, verbose_name='Total compensation'),
        ),
    ]
