# Generated by Django 2.1.1 on 2019-07-22 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_companies', '0018_auto_20180918_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalofficersalary',
            name='customrank',
            field=models.IntegerField(blank=True, db_column='CustomRank', help_text='Override the default ranking for the year.  Overall, this is helpful for previous years, as data can get updated and rankings can change.', null=True, verbose_name='Custom rank'),
        ),
        migrations.AddField(
            model_name='officersalary',
            name='customrank',
            field=models.IntegerField(blank=True, db_column='CustomRank', help_text='Override the default ranking for the year.  Overall, this is helpful for previous years, as data can get updated and rankings can change.', null=True, verbose_name='Custom rank'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='publishyear',
            field=models.IntegerField(db_column='PublishYear', default=2019, help_text='The calendar year this data will be published.', verbose_name='Publish year'),
        ),
        migrations.AlterField(
            model_name='finances',
            name='publishyear',
            field=models.IntegerField(db_column='PublishYear', default=2019, help_text='Year this data will be published.', verbose_name='Publish year'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalemployees',
            name='publishyear',
            field=models.IntegerField(db_column='PublishYear', default=2019, help_text='The calendar year this data will be published.', verbose_name='Publish year'),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='publishyear',
            field=models.IntegerField(db_column='PublishYear', default=2019, help_text='Year this data will be published.', verbose_name='Publish year'),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitfinances',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalnonprofitsalary',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalofficer',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalofficersalary',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nonprofitfinances',
            name='coid',
            field=models.ForeignKey(db_column='COID', help_text='Company associated with this record.', on_delete=django.db.models.deletion.CASCADE, related_name='nonprofit_finances_company', to='business_companies.Company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='nonprofitsalary',
            name='officerid',
            field=models.ForeignKey(db_column='OfficerID', help_text='The officer that this data is for.', on_delete=django.db.models.deletion.CASCADE, related_name='nonprofit_officer', to='business_companies.Officer', verbose_name='Officer ID'),
        ),
    ]
