# Generated by Django 2.1.1 on 2019-07-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_companies', '0020_auto_20190722_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finances',
            name='customrank',
            field=models.IntegerField(blank=True, db_column='CustomRank', help_text='Override the default ranking for the year, which is usually by revenue.  Overall, this is helpful for previous years, as data will can get updated and companies move in and out of the state.', null=True, verbose_name='Custom rank'),
        ),
        migrations.AlterField(
            model_name='historicalfinances',
            name='customrank',
            field=models.IntegerField(blank=True, db_column='CustomRank', help_text='Override the default ranking for the year, which is usually by revenue.  Overall, this is helpful for previous years, as data will can get updated and companies move in and out of the state.', null=True, verbose_name='Custom rank'),
        ),
    ]
