# Generated by Django 2.1.1 on 2019-07-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_companies', '0021_auto_20190722_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalofficersalary',
            name='customrank',
            field=models.IntegerField(blank=True, help_text='Override the default ranking for the year.  Overall, this is helpful for previous years, as data can get updated and rankings can change.', null=True, verbose_name='Custom rank'),
        ),
        migrations.AlterField(
            model_name='officersalary',
            name='customrank',
            field=models.IntegerField(blank=True, help_text='Override the default ranking for the year.  Overall, this is helpful for previous years, as data can get updated and rankings can change.', null=True, verbose_name='Custom rank'),
        ),
    ]
